### ISSUE TITLE
LoginView의 Main.storyboard에 ViewController가 2개?

### ISSUE THREAD

**Issue by yoonhg84** [bluelocate/boostcamp_iOS_kwonbyungsoo#2]
Main.Storyboard의 ViewController는 왜 2개인가요?

**Comment by yoonhg84** [comment]
상단에 있는 "스택뷰"는 왜 있나요?

**Comment by bluelocate** [comment]
스택뷰를 사용한 것과 사용하지 않은 오토레이아웃을 구별하기 위해 배치했습니다!
스택뷰를 사용하는것과 사용하지 않는것의 연습을 위해 뷰 컨트롤러를 구성해 보았습니다.
